ktor {
  deployment {
    port = 8080
  }

  database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5432/tictactoe"
    url = ${?DB_URL}
    user = "postgres"
    user = ${?DB_USER}
    password = "postgres"
    password = ${?DB_PASSWORD}
  }

  application {
    modules = [
      nukinderuru.web.module.ApplicationModuleKt.configureDatabase,
      nukinderuru.web.module.ApplicationModuleKt.configureSerialization,
      nukinderuru.web.module.ApplicationModuleKt.configureMonitoring,
      nukinderuru.web.module.ApplicationModuleKt.configureAuthentication,
      nukinderuru.web.module.ApplicationModuleKt.configureRouting
    ]
  }
}
